### ISSUE TITLE
Create a Login page

### ISSUE THREAD

**Issue by maaxow** [maaxow/BringBreakfast#1]
Create a form for the home page to :

- login (user/password)
- create an account

**EDIT** : login page created.
- Add Angular Material design to the form

**Comment by NitinNair89** [comment]
Hi @maaxow 
Could you please elaborate about this project? I would love to collaborate with you. :smiley:

**Comment by atharvathombre** [comment]
hey i would also to contribute to this project.Although, I am a beginner but still will get to learn things from contributing.

**Comment by Aggarwal-dev** [comment]
Hi @maaxow 
I would like to work in collaboration with you. Kindly share more info regarding the project.

**Comment by maaxow** [comment]
I just writing a Specifications file :

[SPEC.md](https://github.com/maaxow/BringBreakfast/blob/master/SPEC.md)

**Comment by atharvathombre** [comment]
Is it a Website or desktop application or a android application? Please
specify!!

**Comment by atharvathombre** [comment]
@maaxow we have to make login form in html? please specify!

**Comment by NitinNair89** [comment]
> @maaxow we have to make login form in html? please specify!

It depends on how you want to have it. We can have the Login form as a modal, or create a login component that serves the login functionality.

**Comment by maaxow** [comment]
Yes Html

**Comment by NitinNair89** [comment]
> Yes Html

Yes. Are you planning to use some frameworks like Angular-material or Bootstrap or MDBootstrap or custom styling?

You can mention the details in the SPEC doc. :smiley:

**Comment by maaxow** [comment]
Oh yes, i forgot this point. Angular Material is my choice 😄

**Comment by maaxow** [comment]
I have created the page. But it's very simple, there are no CSS. If you want, you can add material in this form 😄

**Comment by BlackDevil98** [comment]
i think i make a simple login page design...
