### ISSUE TITLE
Create backend folder

### ISSUE THREAD

**Issue by maaxow** [maaxow/BringBreakfast#12]
- [x] use maven
- [x] Add latest spring
- [x] use spring data, spring security

**Comment by basalt79** [comment]
may i support here a little bit..

what are the requirement?
so why spring data ?

**Comment by maaxow** [comment]
I'm using Java and Spring in my job, so I know this, and I can make this easily.
 Have you a better idea to replace Spring ? Replace Java ? 
I'm open to proposals 😄
